// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/herdiagusthio/flight-search-system/domain (interfaces: FlightProvider,ProviderRegistry)
//
// Generated by this command:
//
//	mockgen -destination=domain/provider_mock.go -package=domain github.com/herdiagusthio/flight-search-system/domain FlightProvider,ProviderRegistry
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFlightProvider is a mock of FlightProvider interface.
type MockFlightProvider struct {
	ctrl     *gomock.Controller
	recorder *MockFlightProviderMockRecorder
	isgomock struct{}
}

// MockFlightProviderMockRecorder is the mock recorder for MockFlightProvider.
type MockFlightProviderMockRecorder struct {
	mock *MockFlightProvider
}

// NewMockFlightProvider creates a new mock instance.
func NewMockFlightProvider(ctrl *gomock.Controller) *MockFlightProvider {
	mock := &MockFlightProvider{ctrl: ctrl}
	mock.recorder = &MockFlightProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlightProvider) EXPECT() *MockFlightProviderMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockFlightProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockFlightProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockFlightProvider)(nil).Name))
}

// Search mocks base method.
func (m *MockFlightProvider) Search(ctx context.Context, criteria SearchCriteria) ([]Flight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, criteria)
	ret0, _ := ret[0].([]Flight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockFlightProviderMockRecorder) Search(ctx, criteria any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockFlightProvider)(nil).Search), ctx, criteria)
}

// MockProviderRegistry is a mock of ProviderRegistry interface.
type MockProviderRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockProviderRegistryMockRecorder
	isgomock struct{}
}

// MockProviderRegistryMockRecorder is the mock recorder for MockProviderRegistry.
type MockProviderRegistryMockRecorder struct {
	mock *MockProviderRegistry
}

// NewMockProviderRegistry creates a new mock instance.
func NewMockProviderRegistry(ctrl *gomock.Controller) *MockProviderRegistry {
	mock := &MockProviderRegistry{ctrl: ctrl}
	mock.recorder = &MockProviderRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderRegistry) EXPECT() *MockProviderRegistryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockProviderRegistry) Get(name string) FlightProvider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", name)
	ret0, _ := ret[0].(FlightProvider)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockProviderRegistryMockRecorder) Get(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProviderRegistry)(nil).Get), name)
}

// GetAll mocks base method.
func (m *MockProviderRegistry) GetAll() []FlightProvider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]FlightProvider)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockProviderRegistryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockProviderRegistry)(nil).GetAll))
}

// Names mocks base method.
func (m *MockProviderRegistry) Names() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Names")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Names indicates an expected call of Names.
func (mr *MockProviderRegistryMockRecorder) Names() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Names", reflect.TypeOf((*MockProviderRegistry)(nil).Names))
}

// Register mocks base method.
func (m *MockProviderRegistry) Register(provider FlightProvider) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", provider)
}

// Register indicates an expected call of Register.
func (mr *MockProviderRegistryMockRecorder) Register(provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockProviderRegistry)(nil).Register), provider)
}
