// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/herdiagusthio/flight-search-system/internal/usecase (interfaces: FlightSearchUseCase)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/flight_search_mock.go -package=usecase github.com/herdiagusthio/flight-search-system/internal/usecase FlightSearchUseCase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/herdiagusthio/flight-search-system/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFlightSearchUseCase is a mock of FlightSearchUseCase interface.
type MockFlightSearchUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockFlightSearchUseCaseMockRecorder
	isgomock struct{}
}

// MockFlightSearchUseCaseMockRecorder is the mock recorder for MockFlightSearchUseCase.
type MockFlightSearchUseCaseMockRecorder struct {
	mock *MockFlightSearchUseCase
}

// NewMockFlightSearchUseCase creates a new mock instance.
func NewMockFlightSearchUseCase(ctrl *gomock.Controller) *MockFlightSearchUseCase {
	mock := &MockFlightSearchUseCase{ctrl: ctrl}
	mock.recorder = &MockFlightSearchUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlightSearchUseCase) EXPECT() *MockFlightSearchUseCaseMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockFlightSearchUseCase) Search(ctx context.Context, criteria domain.SearchCriteria, opts SearchOptions) (*domain.SearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, criteria, opts)
	ret0, _ := ret[0].(*domain.SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockFlightSearchUseCaseMockRecorder) Search(ctx, criteria, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockFlightSearchUseCase)(nil).Search), ctx, criteria, opts)
}
